import * as THREE from "three";
import { VFXProps, VFXElement } from "./types";
export default class VFXPlayer {
    private canvas;
    renderer: THREE.WebGLRenderer;
    camera: THREE.Camera;
    isPlaying: boolean;
    pixelRatio: number;
    elements: VFXElement[];
    w: number;
    h: number;
    scrollX: number;
    scrollY: number;
    mouseX: number;
    mouseY: number;
    constructor(canvas: HTMLCanvasElement);
    destroy(): void;
    private updateCanvasSize;
    private resize;
    private scroll;
    private mousemove;
    private rerender;
    addElement(element: HTMLElement, opts?: VFXProps): Promise<void>;
    removeElement(element: HTMLElement): void;
    updateElement(element: HTMLElement): Promise<void>;
    play(): void;
    stop(): void;
    private playLoop;
    private isRectInViewport;
}
