name: "Visual Regression Test"
on:
  issue_comment:
    types: [created]
jobs:
  chromatic:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/vrt' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - name: Set pending status
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: 'pending',
              context: 'VRT',
              description: 'VRT is running'
            });
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: "**/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/storybook
          buildScriptName: build-storybook
      - name: Update status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |-
            const { owner, repo } = context.repo;
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: '${{ steps.chromatic.outcome }}' === 'success' ? 'success' : 'failure',
              context: 'Chromatic',
              description: '${{ steps.chromatic.outcome }}' === 'success'
                ? 'VRT passed'
                : 'VRT failed'
            });
