name: "Visual Regression Test"
on:
  issue_comment:
    types: [created]
jobs:
  vrt:
    # Trigger by PullRequest comments
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/vrt' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        uses: actions/github-script@v7
        id: get-pr
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: context.issue.number
            });
            return pr.data;
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: "**/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
